name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
    - name: Checkout Master
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Build Master
      run: cargo build --release
    - name: Bench Master
      run: cargo bench
    - name: Checkout Non-Lazy
      uses: actions/checkout@v3
      with:
        ref: non-lazy
    - name: Build Non-Lazy
      run: cargo build --release
    - name: Bench Non-Lazy
      run: cargo bench
